### ISSUE TITLE
ImportError: cannot import name '_generate_dropout_ones'

### ISSUE THREAD

**Issue by rorycawley** [titu1994/Keras-IndRNN#3]
I'm using Keras 2.1.5 but i am getting this error when I try to run IndRNN:

ImportError                               Traceback (most recent call last)
<ipython-input-15-1e491c48ac7f> in <module>()
     11 from keras.legacy import interfaces
     12 from keras.layers import RNN
---> 13 from keras.layers.recurrent import _generate_dropout_mask, _generate_dropout_ones
     14 
     15 class IndRNNCell(Layer):

ImportError: cannot import name '_generate_dropout_ones'

**Comment by kepengxu** [comment]
I also find this problem,and can't find solutionfor it

**Comment by kepengxu** [comment]
I find the reason of this problem is keras2.1.6 remove _gemerate_dropout_ones,and it out of index

**Comment by ctudoudou** [comment]
I think u can try using keras2.1.5, that can run.

**Comment by MaximumEndurance** [comment]
`generate_dropout_ones` has been depreciated and `K.ones_like()` is used in turn. Refer issue [#9892](https://github.com/keras-team/keras/commit/e73199d413395d7ede0dd86c06f7a9ad2d1fee17) in keras.
Changes have already been made in the code and this issue might now be closed if you deem fit. @titu1994
