### ISSUE TITLE
How to do "Stateful" prediction

### ISSUE THREAD

**Issue by valendin** [titu1994/Keras-IndRNN#5]
Hi Somshubra,

I was wondering if you could give me some advice. I'm trying to implement auto-regressive prediction. I've trained the model to "predict next" value in a sequence by setting the target to be the sample shifted by one. With vanilla LSTM, you can set Stateful=True and then recursively feed the last prediction as the new input and generate the desired sequence. This works before the LSTM keeps the last state after predicting (until you manually reset it). 

How to do this with IndRNN? Would I have to save the final state at every step and then feed it as a parameter of the next prediction step? Thank you for your suggestions!

Best,
Jan

**Comment by titu1994** [comment]
Since the cell wrapping behaviour is exactly the same as for LSTM, I think you can just drop IndRNNCell as a replacement for LSTMCell, and it should work. 

If you are working with the layer directly, since it inherits Recurrent base later, you can do exactly like you would with an LSTM.

**Comment by valendin** [comment]
Sorry for this basic question, but how do I create this LSTM-like layer with IndRNN as the cell type?

**Comment by titu1994** [comment]
Basically, whatever code you had for stateful with LSTM, just replace it with IndRNN. It should work.
