### ISSUE TITLE
If I specify the timestep, do I need to adjust max clip range?

### ISSUE THREAD

**Issue by wilkinsmicawber** [titu1994/Keras-IndRNN#8]
I don't understand the last paragraph of the notes. If I specify the timesteps during training, do I need to change the default max clipping range of 1?

**Comment by titu1994** [comment]
It is best to always supply the clipping range irrespective of whether you are on training or evaluation mode. The infinite timesteps clipping range is non optimal. 

Even for relu, it is advisable to simply pass 2^(1/T) as max.

**Comment by wilkinsmicawber** [comment]
Thank you. Looking through the code and reading your response made the issue clear.
